http.host: "0.0.0.0"
xpack.monitoring.enabled: false
path.config: "/usr/share/logstash/pipeline"
path.logs: "/usr/share/logstash/logs"
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50
queue.type: persisted
queue.max_bytes: 1gb
dead_letter_queue.enable: true
log.level: info
