groups:
  - name: refnet_alerts
    rules:
      # API サービスアラート
      - alert: APIServiceDown
        expr: up{job="refnet-api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "RefNet API service is down"
          description: "API service has been down for more than 1 minute"

      - alert: HighAPIResponseTime
        expr: http_request_duration_seconds{quantile="0.95"} > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High API response time"
          description: "95th percentile response time is {{ $value }}s"

      # データベースアラート
      - alert: DatabaseDown
        expr: up{job="postgres"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL database is down"
          description: "Database has been unreachable for more than 30 seconds"

      - alert: HighDatabaseConnections
        expr: pg_stat_database_numbackends > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High database connection count"
          description: "Database has {{ $value }} active connections"

      # システムリソースアラート
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is {{ $value }}%"

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}%"

      - alert: LowDiskSpace
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 90
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space"
          description: "Disk usage is {{ $value }}%"

      # Celeryワーカーアラート
      - alert: CeleryWorkerDown
        expr: flower_workers{state="ONLINE"} < 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Celery worker is down"
          description: "No online Celery workers detected"

      - alert: HighTaskFailureRate
        expr: rate(celery_task_total{state="FAILURE"}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High task failure rate"
          description: "Task failure rate is {{ $value }} tasks/sec"

      - alert: CeleryQueueBacklog
        expr: celery_queue_length > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Celery queue backlog"
          description: "Queue {{ $labels.queue }} has {{ $value }} pending tasks"

      - alert: CeleryTaskTimeout
        expr: celery_task_duration_seconds > 300
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Celery task timeout"
          description: "Task {{ $labels.task }} is taking {{ $value }}s to complete"

      - alert: CeleryBeatScheduleFailure
        expr: rate(celery_beat_schedule_runs_total{state="FAILURE"}[10m]) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Celery Beat schedule failure"
          description: "Scheduled task {{ $labels.task }} is failing"

      # Redis アラート
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis service has been unreachable for more than 30 seconds"

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis high memory usage"
          description: "Redis memory usage is {{ $value | humanizePercentage }}"

      - alert: RedisHighConnections
        expr: redis_connected_clients > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis high connection count"
          description: "Redis has {{ $value }} connected clients"

      # セキュリティアラート
      - alert: UnauthorizedAPIAccess
        expr: increase(http_requests_total{status=~"401|403"}[5m]) > 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Unauthorized API access attempts"
          description: "{{ $value }} unauthorized access attempts in the last 5 minutes"

      - alert: DatabaseConnectionSpike
        expr: increase(pg_stat_database_numbackends[5m]) > 50
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Database connection spike"
          description: "Database connections increased by {{ $value }} in 5 minutes"

      - alert: SuspiciousActivityPattern
        expr: increase(http_requests_total{status=~"4.."}[1m]) > 100
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Suspicious activity pattern detected"
          description: "{{ $value }} 4xx errors in the last minute"

      # ビジネスロジックアラート
      - alert: PaperProcessingFailure
        expr: rate(celery_task_total{task=~".*paper.*", state="FAILURE"}[10m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Paper processing failure rate high"
          description: "Paper processing tasks are failing at {{ $value }} tasks/sec"

      - alert: ScrapingServiceDown
        expr: up{job="refnet-crawler"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Paper scraping service is down"
          description: "Crawler service has been unreachable for more than 2 minutes"

      - alert: AIServiceResponseTime
        expr: http_request_duration_seconds{job="refnet-summarizer", quantile="0.95"} > 30
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "AI service slow response"
          description: "AI summarization service 95th percentile response time is {{ $value }}s"

      # データ整合性アラート
      - alert: DatabaseReplicationLag
        expr: pg_stat_replication_lag_seconds > 60
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Database replication lag"
          description: "Database replication lag is {{ $value }}s"

      - alert: BackupFailure
        expr: time() - backup_last_success_timestamp > 86400
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Backup failure"
          description: "Last successful backup was {{ $value | humanizeDuration }} ago"

      - alert: LogVolumeAnomaly
        expr: increase(log_entries_total[5m]) > 1000
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Log volume anomaly"
          description: "Log volume increased by {{ $value }} entries in 5 minutes"
