global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus自体の監視
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # システムメトリクス
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # RefNet APIサービス
  - job_name: 'refnet-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: /metrics
    scrape_interval: 30s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Nginx
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: /nginx_status

  # Celery Workers
  - job_name: 'celery-flower'
    static_configs:
      - targets: ['flower:5555']
    metrics_path: /api/workers

  # Celery Exporter
  - job_name: 'celery-exporter'
    static_configs:
      - targets: ['celery-exporter:9540']
